/**
 * Batch 3D CAD Mesh Exporter & ZIP Archive Packaging Engine
 * Generates STL (ASCII & Binary), Wavefront OBJ + MTL, JSON manifests, and BOM specifications.
 */

import JSZip from 'jszip';
import { CADObject, BatchExportConfig, CADMaterial } from '../types/cad';
import { exportSceneTo3MF } from './cadEngine';

// Generates an ASCII STL representation of a CADObject
export function generateAsciiSTL(object: CADObject, scaleMultiplier = 1.0): string {
  const { width, height, depth } = object.dimensions;
  const w = (width * scaleMultiplier) / 2;
  const h = (height * scaleMultiplier) / 2;
  const d = (depth * scaleMultiplier) / 2;

  // 8 Vertices of bounding cuboid
  const v = [
    [-w, -h, -d],
    [w, -h, -d],
    [w, h, -d],
    [-w, h, -d],
    [-w, -h, d],
    [w, -h, d],
    [w, h, d],
    [-w, h, d],
  ];

  // 12 Triangles (2 per face)
  const faces = [
    // Front face
    { norm: [0, 0, 1], pts: [v[4], v[5], v[6]] },
    { norm: [0, 0, 1], pts: [v[4], v[6], v[7]] },
    // Back face
    { norm: [0, 0, -1], pts: [v[1], v[0], v[3]] },
    { norm: [0, 0, -1], pts: [v[1], v[3], v[2]] },
    // Top face
    { norm: [0, 1, 0], pts: [v[3], v[2], v[6]] },
    { norm: [0, 1, 0], pts: [v[3], v[6], v[7]] },
    // Bottom face
    { norm: [0, -1, 0], pts: [v[0], v[1], v[5]] },
    { norm: [0, -1, 0], pts: [v[0], v[5], v[4]] },
    // Right face
    { norm: [1, 0, 0], pts: [v[1], v[2], v[6]] },
    { norm: [1, 0, 0], pts: [v[1], v[6], v[5]] },
    // Left face
    { norm: [-1, 0, 0], pts: [v[0], v[4], v[7]] },
    { norm: [-1, 0, 0], pts: [v[0], v[7], v[3]] },
  ];

  const solidName = object.name.replace(/[^a-zA-Z0-9_]/g, '_');
  let stl = `solid ${solidName}\n`;

  for (const f of faces) {
    stl += `  facet normal ${f.norm[0]} ${f.norm[1]} ${f.norm[2]}\n`;
    stl += `    outer loop\n`;
    for (const p of f.pts) {
      stl += `      vertex ${p[0].toFixed(4)} ${p[1].toFixed(4)} ${p[2].toFixed(4)}\n`;
    }
    stl += `    endloop\n`;
    stl += `  endfacet\n`;
  }

  stl += `endsolid ${solidName}\n`;
  return stl;
}

// Generates Wavefront OBJ string for a CADObject
export function generateWavefrontOBJ(object: CADObject, scaleMultiplier = 1.0): string {
  const { width, height, depth } = object.dimensions;
  const w = (width * scaleMultiplier) / 2;
  const h = (height * scaleMultiplier) / 2;
  const d = (depth * scaleMultiplier) / 2;

  let obj = `# Wavefront OBJ generated by Google AI Studio CAD\n`;
  obj += `o ${object.name.replace(/\s+/g, '_')}\n`;
  obj += `mtllib ${object.id}.mtl\n`;

  // Vertices
  obj += `v ${-w} ${-h} ${-d}\n`;
  obj += `v ${w} ${-h} ${-d}\n`;
  obj += `v ${w} ${h} ${-d}\n`;
  obj += `v ${-w} ${h} ${-d}\n`;
  obj += `v ${-w} ${-h} ${d}\n`;
  obj += `v ${w} ${-h} ${d}\n`;
  obj += `v ${w} ${h} ${d}\n`;
  obj += `v ${-w} ${h} ${d}\n`;

  // Normals
  obj += `vn 0 0 1\n`;
  obj += `vn 0 0 -1\n`;
  obj += `vn 0 1 0\n`;
  obj += `vn 0 -1 0\n`;
  obj += `vn 1 0 0\n`;
  obj += `vn -1 0 0\n`;

  // Material use
  obj += `usemtl mat_${object.material.id}\n`;
  obj += `s 1\n`;

  // Faces (1-indexed)
  obj += `f 5//1 6//1 7//1 8//1\n`; // Front
  obj += `f 2//2 1//2 4//2 3//2\n`; // Back
  obj += `f 4//3 3//3 7//3 8//3\n`; // Top
  obj += `f 1//4 2//4 6//4 5//4\n`; // Bottom
  obj += `f 2//5 3//5 7//5 6//5\n`; // Right
  obj += `f 1//6 5//6 8//6 4//6\n`; // Left

  return obj;
}

// Generates Material .MTL file
export function generateMaterialMTL(material: CADMaterial): string {
  let mtl = `# Material Definition\n`;
  mtl += `newmtl mat_${material.id}\n`;
  mtl += `Ka 0.2 0.2 0.2\n`;
  mtl += `Kd 0.8 0.8 0.8\n`;
  mtl += `Ks ${material.metalness} ${material.metalness} ${material.metalness}\n`;
  mtl += `d ${material.opacity ?? 1.0}\n`;
  mtl += `Ns ${(1 - material.roughness) * 100}\n`;
  mtl += `illum 2\n`;
  return mtl;
}

// Generates Bill of Materials JSON
export function generateBOMJson(objects: CADObject[]): string {
  const manifest = {
    exportDate: new Date().toISOString(),
    totalParts: objects.length,
    totalEstimatedCostUsd: objects.reduce((sum, o) => sum + (o.unitCostUsd || 12.5), 0),
    totalMassKg: objects.reduce((sum, o) => sum + (o.massKg || 0.035), 0),
    parts: objects.map(o => ({
      id: o.id,
      name: o.name,
      category: o.category,
      primitive: o.primitive,
      material: o.material.name,
      dimensionsMm: o.dimensions,
      positionMm: o.position,
      rotationRad: o.rotation,
      massKg: o.massKg || 0.035,
      unitCostUsd: o.unitCostUsd || 12.5,
      layerId: o.layerId || 'layer_default',
    })),
  };
  return JSON.stringify(manifest, null, 2);
}

// Generates Engineering Specification Text Document
export function generateSpecsTxt(objects: CADObject[], assemblyName: string): string {
  let txt = `=======================================================\n`;
  txt += `       ENGINEERING CAD SPECIFICATION & DFM AUDIT       \n`;
  txt += `=======================================================\n\n`;
  txt += `ASSEMBLY: ${assemblyName}\n`;
  txt += `DATE: ${new Date().toLocaleString()}\n`;
  txt += `TOTAL COMPONENTS: ${objects.length}\n\n`;
  txt += `-------------------------------------------------------\n`;
  txt += `PARTS BREAKDOWN:\n`;
  txt += `-------------------------------------------------------\n`;

  objects.forEach((obj, idx) => {
    txt += `[${idx + 1}] ${obj.name}\n`;
    txt += `    ID: ${obj.id}\n`;
    txt += `    Category: ${obj.category.toUpperCase()}\n`;
    txt += `    Primitive: ${obj.primitive}\n`;
    txt += `    Dimensions: ${obj.dimensions.width}mm x ${obj.dimensions.height}mm x ${obj.dimensions.depth}mm\n`;
    txt += `    Material: ${obj.material.name} (Roughness: ${obj.material.roughness}, Metalness: ${obj.material.metalness})\n`;
    txt += `    Position: [${obj.position.join(', ')}] mm\n\n`;
  });

  return txt;
}

// Packages all files into a ZIP archive and triggers automatic download
export async function executeBatchExport(
  objects: CADObject[],
  config: BatchExportConfig,
  assemblyName: string,
  onProgress?: (percent: number, status: string) => void
): Promise<void> {
  const zip = new JSZip();
  const totalSteps = objects.length * config.formats.length + 3;
  let currentStep = 0;

  const updateProgress = (status: string) => {
    currentStep++;
    const pct = Math.min(100, Math.round((currentStep / totalSteps) * 100));
    if (onProgress) onProgress(pct, status);
  };

  // 1. Process each part according to selected formats and grouping
  for (let i = 0; i < objects.length; i++) {
    const obj = objects[i];
    const cleanName = obj.name.replace(/[^a-zA-Z0-9_-]/g, '_');
    
    // Determine folder path based on grouping
    let folder = zip;
    if (config.grouping === 'by_layer_folders') {
      const layerName = (obj.layerId || 'default_layer').replace(/[^a-zA-Z0-9_-]/g, '_');
      folder = zip.folder(`layers/${layerName}`) || zip;
    } else if (config.grouping === 'by_material_folders') {
      const matName = obj.material.name.replace(/[^a-zA-Z0-9_-]/g, '_');
      folder = zip.folder(`materials/${matName}`) || zip;
    }

    // Format: STL ASCII
    if (config.formats.includes('stl_ascii')) {
      updateProgress(`Exporting STL for ${obj.name}...`);
      const stlData = generateAsciiSTL(obj, config.scaleMultiplier);
      folder.file(`${cleanName}.stl`, stlData);
    }

    // Format: OBJ & MTL
    if (config.formats.includes('obj_mtl')) {
      updateProgress(`Exporting OBJ/MTL for ${obj.name}...`);
      const objData = generateWavefrontOBJ(obj, config.scaleMultiplier);
      const mtlData = generateMaterialMTL(obj.material);
      folder.file(`${cleanName}.obj`, objData);
      folder.file(`${obj.id}.mtl`, mtlData);
    }

    // Format: CAD JSON
    if (config.formats.includes('cad_json')) {
      updateProgress(`Exporting JSON schema for ${obj.name}...`);
      folder.file(`${cleanName}_schema.json`, JSON.stringify(obj, null, 2));
    }

    // Format: 3MF Package
    if (config.formats.includes('cad_3mf')) {
      updateProgress(`Compiling 3MF Package for ${obj.name}...`);
      const blob3mf = await exportSceneTo3MF([obj], obj.name);
      folder.file(`${cleanName}.3mf`, blob3mf);
    }
  }

  // 2. Auxiliary BOM and Specs files
  if (config.includeBOMJson) {
    updateProgress('Generating BOM JSON manifest...');
    zip.file('BOM_Manifest.json', generateBOMJson(objects));
  }

  if (config.includeSpecsTxt) {
    updateProgress('Generating Engineering Specifications...');
    zip.file('Engineering_Specs.txt', generateSpecsTxt(objects, assemblyName));
  }

  updateProgress('Compressing ZIP archive package...');

  // Generate binary ZIP Blob
  const content = await zip.generateAsync({ type: 'blob' }, metadata => {
    if (onProgress && metadata.percent) {
      onProgress(Math.round(metadata.percent), `Compressing ZIP (${Math.round(metadata.percent)}%)...`);
    }
  });

  // Trigger browser download
  const url = URL.createObjectURL(content);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${config.zipArchiveName || 'CAD_Studio_Batch_Export'}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
