import { CADMaterial } from '../types/cad';

export const MATERIAL_PRESETS: Record<string, CADMaterial> = {
  // --- TECHNOLOGY & ELECTRONICS MATERIALS ---
  anodized_aluminum_spacegray: {
    id: 'mat_al_spacegray',
    name: 'Space Gray Aluminum',
    type: 'anodized_aluminum',
    color: '#383b42',
    roughness: 0.28,
    metalness: 0.88,
    clearcoat: 0.1,
  },
  anodized_aluminum_silver: {
    id: 'mat_al_silver',
    name: 'Silver Aluminum',
    type: 'anodized_aluminum',
    color: '#d6dbe0',
    roughness: 0.22,
    metalness: 0.92,
  },
  anodized_aluminum_midnight: {
    id: 'mat_al_midnight',
    name: 'Midnight Blue Aluminum',
    type: 'anodized_aluminum',
    color: '#1a2233',
    roughness: 0.25,
    metalness: 0.85,
  },
  polished_titanium: {
    id: 'mat_titanium',
    name: 'Natural Titanium',
    type: 'polished_metal',
    color: '#8b8882',
    roughness: 0.18,
    metalness: 0.95,
  },
  matte_black_polycarbonate: {
    id: 'mat_polycarbonate_black',
    name: 'Matte Stealth Black',
    type: 'matte_plastic',
    color: '#1f1f23',
    roughness: 0.55,
    metalness: 0.05,
  },
  cyber_white_chassis: {
    id: 'mat_chassis_white',
    name: 'Ceramic White',
    type: 'glossy_ceramic',
    color: '#f3f4f6',
    roughness: 0.12,
    metalness: 0.08,
    clearcoat: 0.8,
  },
  oled_screen_active: {
    id: 'mat_screen_active',
    name: 'OLED Display (Active)',
    type: 'tinted_glass',
    color: '#090d16',
    roughness: 0.04,
    metalness: 0.2,
    emissive: '#1e3a8a',
    emissiveIntensity: 0.6,
  },
  oled_screen_cyber: {
    id: 'mat_screen_cyber',
    name: 'Cyber HUD Display',
    type: 'tinted_glass',
    color: '#05181b',
    roughness: 0.05,
    metalness: 0.1,
    emissive: '#06b6d4',
    emissiveIntensity: 0.85,
  },
  sapphire_camera_glass: {
    id: 'mat_camera_glass',
    name: 'Sapphire Lens Glass',
    type: 'clear_glass',
    color: '#1e293b',
    roughness: 0.02,
    metalness: 0.1,
    transparent: true,
    opacity: 0.75,
    transmission: 0.9,
  },
  pcb_matte_black: {
    id: 'mat_pcb_black',
    name: 'FR-4 PCB (Matte Black)',
    type: 'pcb_black',
    color: '#18191c',
    roughness: 0.45,
    metalness: 0.15,
    texturePattern: 'pcb_grid',
  },
  pcb_classic_green: {
    id: 'mat_pcb_green',
    name: 'FR-4 PCB (Industrial Green)',
    type: 'pcb_green',
    color: '#0e4429',
    roughness: 0.4,
    metalness: 0.2,
    texturePattern: 'pcb_grid',
  },
  gold_electroless_trace: {
    id: 'mat_gold_trace',
    name: 'ENIG Gold Plating',
    type: 'gold_trace',
    color: '#d4af37',
    roughness: 0.15,
    metalness: 0.98,
  },
  copper_heatsink: {
    id: 'mat_copper',
    name: 'Pure Copper Heatsink',
    type: 'copper',
    color: '#b86638',
    roughness: 0.25,
    metalness: 0.95,
  },
  carbon_fiber_composite: {
    id: 'mat_carbon_fiber',
    name: 'Carbon Fiber Weave',
    type: 'carbon_fiber',
    color: '#151518',
    roughness: 0.35,
    metalness: 0.4,
    texturePattern: 'carbon',
  },
  led_indicator_cyan: {
    id: 'mat_led_cyan',
    name: 'Status LED (Cyan Neon)',
    type: 'led_emissive',
    color: '#06b6d4',
    roughness: 0.1,
    metalness: 0.1,
    emissive: '#00f0ff',
    emissiveIntensity: 1.5,
  },
  led_indicator_emerald: {
    id: 'mat_led_emerald',
    name: 'Power LED (Emerald)',
    type: 'led_emissive',
    color: '#10b981',
    roughness: 0.1,
    metalness: 0.1,
    emissive: '#10b981',
    emissiveIntensity: 1.5,
  },
  led_indicator_orange: {
    id: 'mat_led_orange',
    name: 'Thermal Warning LED',
    type: 'led_emissive',
    color: '#f97316',
    roughness: 0.1,
    metalness: 0.1,
    emissive: '#f97316',
    emissiveIntensity: 1.5,
  },
  silicone_rubber_grip: {
    id: 'mat_silicone',
    name: 'Tactile Silicone Rubber',
    type: 'rubber_grip',
    color: '#2a2b30',
    roughness: 0.85,
    metalness: 0.02,
  },

  // --- ARCHITECTURAL & BUILDING MATERIALS ---
  architectural_concrete: {
    id: 'mat_arch_concrete',
    name: 'Fair-Faced Concrete',
    type: 'concrete',
    color: '#9ca3af',
    roughness: 0.78,
    metalness: 0.02,
    texturePattern: 'concrete_speck',
  },
  warm_oak_timber: {
    id: 'mat_arch_wood',
    name: 'Natural Scandinavian Oak',
    type: 'warm_wood',
    color: '#bfa074',
    roughness: 0.55,
    metalness: 0.05,
    texturePattern: 'wood_grain',
  },
  curtain_wall_glass: {
    id: 'mat_arch_glass',
    name: 'Low-E Solar Glazing',
    type: 'tinted_glass',
    color: '#93c5fd',
    roughness: 0.03,
    metalness: 0.15,
    transparent: true,
    opacity: 0.45,
    transmission: 0.85,
  },
  corten_steel: {
    id: 'mat_arch_corten',
    name: 'Weathered Corten Steel',
    type: 'steel_beam',
    color: '#7c3a1e',
    roughness: 0.8,
    metalness: 0.7,
  },
  dark_slate_brick: {
    id: 'mat_arch_brick',
    name: 'Anthracite Facing Brick',
    type: 'brick',
    color: '#374151',
    roughness: 0.88,
    metalness: 0.05,
  },
  white_stucco_plaster: {
    id: 'mat_arch_plaster',
    name: 'Mineral White Plaster',
    type: 'white_plaster',
    color: '#f9fafb',
    roughness: 0.82,
    metalness: 0.01,
  },
  structural_steel_dark: {
    id: 'mat_arch_steel',
    name: 'Structural I-Beam Steel',
    type: 'steel_beam',
    color: '#1e232a',
    roughness: 0.35,
    metalness: 0.85,
  },
  pv_solar_cell: {
    id: 'mat_arch_solar',
    name: 'Monocrystalline Solar Panel',
    type: 'polished_metal',
    color: '#111827',
    roughness: 0.15,
    metalness: 0.7,
    emissive: '#1e3a8a',
    emissiveIntensity: 0.2,
  },

  // --- AEROSPACE & STARK LAB ADVANCED MATERIALS ---
  stark_arc_gold_alloy: {
    id: 'mat_stark_gold_titanium',
    name: 'Gold-Titanium Alloy (Mark IV)',
    type: 'polished_metal',
    color: '#d4af37',
    roughness: 0.12,
    metalness: 0.98,
    clearcoat: 0.4,
  },
  stark_crimson_armor: {
    id: 'mat_stark_crimson',
    name: 'Hot-Rod Crimson Enamel',
    type: 'glossy_ceramic',
    color: '#9e1b1b',
    roughness: 0.15,
    metalness: 0.85,
    clearcoat: 0.9,
  },
  arc_reactor_core_glow: {
    id: 'mat_arc_glow',
    name: 'Paladium Arc Reactor Core',
    type: 'led_emissive',
    color: '#06b6d4',
    roughness: 0.05,
    metalness: 0.1,
    emissive: '#38bdf8',
    emissiveIntensity: 2.5,
  },
  holographic_cyan_glass: {
    id: 'mat_holo_glass',
    name: 'JARVIS Hologram Matrix',
    type: 'tinted_glass',
    color: '#0284c7',
    roughness: 0.02,
    metalness: 0.1,
    transparent: true,
    opacity: 0.65,
    transmission: 0.9,
    emissive: '#0284c7',
    emissiveIntensity: 0.8,
  },
  brushed_nickel_plating: {
    id: 'mat_nickel',
    name: 'Brushed Nickel Plating',
    type: 'polished_metal',
    color: '#b0ada7',
    roughness: 0.32,
    metalness: 0.9,
    texturePattern: 'brushed',
  },
  damascus_steel_machined: {
    id: 'mat_damascus',
    name: 'Damascene Pattern Steel',
    type: 'polished_metal',
    color: '#475569',
    roughness: 0.28,
    metalness: 0.92,
  },
  peek_high_temp_polymer: {
    id: 'mat_peek',
    name: 'PEEK High-Temp Polymer',
    type: 'matte_plastic',
    color: '#d5c4a1',
    roughness: 0.42,
    metalness: 0.06,
  },
  delrin_acetal_white: {
    id: 'mat_delrin',
    name: 'Delrin CNC Acetal (White)',
    type: 'matte_plastic',
    color: '#f1f5f9',
    roughness: 0.38,
    metalness: 0.04,
  },
  gorilla_glass_victus: {
    id: 'mat_gorilla_glass',
    name: 'Gorilla Glass Victus 2',
    type: 'clear_glass',
    color: '#0f172a',
    roughness: 0.01,
    metalness: 0.05,
    transparent: true,
    opacity: 0.8,
    transmission: 0.95,
  },
  frosted_diffuser_glass: {
    id: 'mat_frosted_glass',
    name: 'Frosted Opal Diffuser',
    type: 'clear_glass',
    color: '#e2e8f0',
    roughness: 0.6,
    metalness: 0.02,
    transparent: true,
    opacity: 0.7,
    transmission: 0.6,
  },
  graphene_monolayer: {
    id: 'mat_graphene',
    name: 'Graphene Thermal Conductor',
    type: 'carbon_fiber',
    color: '#0a0a0c',
    roughness: 0.2,
    metalness: 0.65,
  },
  laser_crimson_emitter: {
    id: 'mat_laser_crimson',
    name: 'Infrared LIDAR Laser (Crimson)',
    type: 'led_emissive',
    color: '#ef4444',
    roughness: 0.1,
    metalness: 0.1,
    emissive: '#ef4444',
    emissiveIntensity: 2.0,
  },
  brass_precision_bushing: {
    id: 'mat_brass',
    name: 'C360 Machined Brass',
    type: 'polished_metal',
    color: '#d97706',
    roughness: 0.22,
    metalness: 0.94,
  },
};

export type MaterialCategory =
  | 'all'
  | 'metals'
  | 'plastics'
  | 'glass'
  | 'composites'
  | 'emissive'
  | 'architecture';

export interface MaterialCategoryDef {
  key: MaterialCategory;
  name: string;
  description: string;
  ids: string[];
}

export const MATERIAL_CATEGORIES: MaterialCategoryDef[] = [
  {
    key: 'all',
    name: 'All Materials',
    description: 'Complete CAD shader and PBR library',
    ids: Object.keys(MATERIAL_PRESETS),
  },
  {
    key: 'metals',
    name: 'Aerospace & Metals',
    description: 'Titanium, aluminum, gold, copper, brass & steel',
    ids: [
      'anodized_aluminum_spacegray',
      'anodized_aluminum_silver',
      'anodized_aluminum_midnight',
      'polished_titanium',
      'stark_arc_gold_alloy',
      'damascus_steel_machined',
      'gold_electroless_trace',
      'copper_heatsink',
      'brushed_nickel_plating',
      'brass_precision_bushing',
      'corten_steel',
      'structural_steel_dark',
    ],
  },
  {
    key: 'plastics',
    name: 'Polymers & Ceramics',
    description: 'Engineering polycarbonate, PEEK, Delrin, ABS & silicone',
    ids: [
      'matte_black_polycarbonate',
      'cyber_white_chassis',
      'stark_crimson_armor',
      'peek_high_temp_polymer',
      'delrin_acetal_white',
      'silicone_rubber_grip',
    ],
  },
  {
    key: 'glass',
    name: 'Glass & Optics',
    description: 'OLED displays, sapphire lenses, Gorilla Glass & solar glazing',
    ids: [
      'oled_screen_active',
      'oled_screen_cyber',
      'sapphire_camera_glass',
      'gorilla_glass_victus',
      'frosted_diffuser_glass',
      'holographic_cyan_glass',
      'curtain_wall_glass',
    ],
  },
  {
    key: 'composites',
    name: 'Composites & PCB',
    description: 'Carbon fiber, FR-4 PCB, graphene & nanotech substrates',
    ids: [
      'carbon_fiber_composite',
      'graphene_monolayer',
      'pcb_matte_black',
      'pcb_classic_green',
      'gold_electroless_trace',
    ],
  },
  {
    key: 'emissive',
    name: 'Emissive & LEDs',
    description: 'Arc reactor cyan, status LEDs, thermal beacons & lasers',
    ids: [
      'arc_reactor_core_glow',
      'led_indicator_cyan',
      'led_indicator_emerald',
      'led_indicator_orange',
      'laser_crimson_emitter',
      'oled_screen_cyber',
    ],
  },
  {
    key: 'architecture',
    name: 'Architectural & BIM',
    description: 'Fair-faced concrete, Scandinavian oak, brick, plaster & steel',
    ids: [
      'architectural_concrete',
      'warm_oak_timber',
      'curtain_wall_glass',
      'corten_steel',
      'dark_slate_brick',
      'white_stucco_plaster',
      'structural_steel_dark',
      'pv_solar_cell',
    ],
  },
];
