import { CADObject, BuildingConfig } from '../../types/cad';
import { MATERIAL_PRESETS } from '../../utils/materials';

export interface BuildingPresetData {
  config: BuildingConfig;
  objects: CADObject[];
}

export const BUILDING_PRESETS: Record<string, BuildingPresetData> = {
  modern_villa: {
    config: {
      id: 'modern_villa',
      name: 'Cantilever Panorama Villa',
      typology: 'modern_villa',
      description: 'Contemporary two-story luxury residence with fair-faced concrete cantilevers, floor-to-ceiling Low-E glazing, timber terraces, and solar rooftop integration.',
      dimensions: { width: 18, length: 24, stories: 2, storyHeight: 3.5 },
      activeFloor: -1,
      viewMode2D: false,
      timeOfDay: 14.5, // 2:30 PM afternoon sun
      sunIntensity: 1.2,
      shadowsEnabled: true,
      showDimensions: true,
      showFurniture: true,
    },
    objects: [
      // Ground Floor Concrete Slab & Foundation
      {
        id: 'arch_ground_slab',
        name: 'Ground Floor Reinforced Concrete Slab',
        category: 'structure',
        section: 'building',
        primitive: 'slab',
        position: [0, -0.2, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 22, height: 0.4, depth: 26 },
        material: MATERIAL_PRESETS.architectural_concrete,
        visible: true,
        locked: true,
        architecturalProps: { floorLevel: 0, materialCostPerM2: 85, isLoadBearing: true },
      },
      // Wooden Terrace / Decking
      {
        id: 'arch_deck_patio',
        name: 'Outdoor Teak Wooden Terrace',
        category: 'interior',
        section: 'building',
        primitive: 'slab',
        position: [8, -0.05, 4],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 8, height: 0.1, depth: 14 },
        material: MATERIAL_PRESETS.warm_oak_timber,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, materialCostPerM2: 120 },
      },
      // Ground Floor Structural Columns (Dark Steel)
      {
        id: 'arch_col_1',
        name: 'Ground Structural Column A1',
        category: 'structure',
        section: 'building',
        primitive: 'column',
        position: [-6, 1.75, -8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 0.4, height: 3.5, depth: 0.4 },
        material: MATERIAL_PRESETS.structural_steel_dark,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, isLoadBearing: true },
      },
      {
        id: 'arch_col_2',
        name: 'Ground Structural Column A2',
        category: 'structure',
        section: 'building',
        primitive: 'column',
        position: [6, 1.75, -8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 0.4, height: 3.5, depth: 0.4 },
        material: MATERIAL_PRESETS.structural_steel_dark,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, isLoadBearing: true },
      },
      {
        id: 'arch_col_3',
        name: 'Ground Structural Column B1',
        category: 'structure',
        section: 'building',
        primitive: 'column',
        position: [-6, 1.75, 4],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 0.4, height: 3.5, depth: 0.4 },
        material: MATERIAL_PRESETS.structural_steel_dark,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, isLoadBearing: true },
      },
      {
        id: 'arch_col_4',
        name: 'Ground Structural Column B2',
        category: 'structure',
        section: 'building',
        primitive: 'column',
        position: [6, 1.75, 4],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 0.4, height: 3.5, depth: 0.4 },
        material: MATERIAL_PRESETS.structural_steel_dark,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, isLoadBearing: true },
      },
      // North Concrete Solid Shear Wall
      {
        id: 'arch_wall_north',
        name: 'North Insulated Architectural Wall',
        category: 'envelope',
        section: 'building',
        primitive: 'wall',
        position: [0, 1.75, -10],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 16, height: 3.5, depth: 0.35 },
        material: MATERIAL_PRESETS.dark_slate_brick,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, isLoadBearing: true, thermalUValue: 0.18 },
      },
      // West Concrete Wall with Feature Slot
      {
        id: 'arch_wall_west',
        name: 'West Concrete Accent Wall',
        category: 'envelope',
        section: 'building',
        primitive: 'wall',
        position: [-8, 1.75, 0],
        rotation: [0, Math.PI / 2, 0],
        scale: [1, 1, 1],
        dimensions: { width: 20, height: 3.5, depth: 0.35 },
        material: MATERIAL_PRESETS.architectural_concrete,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, isLoadBearing: true },
      },
      // South Panoramic Glass Curtain Wall
      {
        id: 'arch_glazing_south_g',
        name: 'Ground South Floor-to-Ceiling Glazing',
        category: 'envelope',
        section: 'building',
        primitive: 'window',
        position: [0, 1.75, 8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 14, height: 3.4, depth: 0.1 },
        material: MATERIAL_PRESETS.curtain_wall_glass,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, thermalUValue: 1.1 },
      },
      // East Sliding Patio Glass Door
      {
        id: 'arch_glazing_east_g',
        name: 'East Sliding Terrace Glass Doors',
        category: 'envelope',
        section: 'building',
        primitive: 'door',
        position: [8, 1.75, 0],
        rotation: [0, Math.PI / 2, 0],
        scale: [1, 1, 1],
        dimensions: { width: 12, height: 3.4, depth: 0.1 },
        material: MATERIAL_PRESETS.curtain_wall_glass,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0 },
      },
      // First Floor Cantilevered Slab (Inter-floor)
      {
        id: 'arch_first_floor_slab',
        name: 'Level 1 Cantilever Concrete Slab',
        category: 'structure',
        section: 'building',
        primitive: 'slab',
        position: [1, 3.6, 1],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 19, height: 0.35, depth: 22 },
        material: MATERIAL_PRESETS.architectural_concrete,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 1, isLoadBearing: true },
      },
      // Level 1 Master Suite Glass Box
      {
        id: 'arch_l1_glazing_box',
        name: 'Level 1 Panoramic Master Bedroom Glass',
        category: 'envelope',
        section: 'building',
        primitive: 'window',
        position: [2, 5.4, 4],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 13, height: 3.2, depth: 0.1 },
        material: MATERIAL_PRESETS.curtain_wall_glass,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 1 },
      },
      // Level 1 Corten Steel Shading Box
      {
        id: 'arch_l1_corten_frame',
        name: 'Level 1 Corten Steel Sun-Louver Frame',
        category: 'envelope',
        section: 'building',
        primitive: 'wall',
        position: [2, 5.4, 8.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 14.5, height: 3.4, depth: 0.4 },
        material: MATERIAL_PRESETS.corten_steel,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 1 },
      },
      // Level 1 Solid Wood Clad Wing
      {
        id: 'arch_l1_wood_wing',
        name: 'Level 1 Scandinavian Timber Clad Wing',
        category: 'envelope',
        section: 'building',
        primitive: 'wall',
        position: [-4, 5.4, -3],
        rotation: [0, Math.PI / 2, 0],
        scale: [1, 1, 1],
        dimensions: { width: 12, height: 3.2, depth: 0.3 },
        material: MATERIAL_PRESETS.warm_oak_timber,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 1 },
      },
      // Rooftop Slab / Flat Roof
      {
        id: 'arch_roof_slab',
        name: 'Insulated Flat Green Roof & Parapet',
        category: 'structure',
        section: 'building',
        primitive: 'slab',
        position: [0.5, 7.2, 0.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 18, height: 0.3, depth: 21 },
        material: MATERIAL_PRESETS.architectural_concrete,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 2 },
      },
      // Rooftop Photovoltaic Solar Array
      {
        id: 'arch_solar_array',
        name: '12.4 kW High-Efficiency PV Solar Array',
        category: 'custom',
        section: 'building',
        primitive: 'solar_panel',
        position: [-1, 7.5, -3],
        rotation: [-0.18, 0, 0], // Tilted 10 deg South
        scale: [1, 1, 1],
        dimensions: { width: 12, height: 0.1, depth: 8 },
        material: MATERIAL_PRESETS.pv_solar_cell,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 2 },
      },
    ],
  },

  office_pavilion: {
    config: {
      id: 'office_pavilion',
      name: 'High-Tech R&D Innovation Pavilion',
      typology: 'office_pavilion',
      description: 'Double-height commercial engineering pavilion with exposed structural steel trusses, clear low-iron curtain walls, and central collaborative atrium.',
      dimensions: { width: 24, length: 28, stories: 2, storyHeight: 4.2 },
      activeFloor: -1,
      viewMode2D: false,
      timeOfDay: 11.0,
      sunIntensity: 1.1,
      shadowsEnabled: true,
      showDimensions: true,
      showFurniture: true,
    },
    objects: [
      // Base Podium Slab
      {
        id: 'off_podium_slab',
        name: 'Basement & Ground Concrete Podium',
        category: 'structure',
        section: 'building',
        primitive: 'slab',
        position: [0, -0.25, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 28, height: 0.5, depth: 32 },
        material: MATERIAL_PRESETS.architectural_concrete,
        visible: true,
        locked: true,
        architecturalProps: { floorLevel: 0, isLoadBearing: true },
      },
      // 8 Heavy Structural Steel Columns
      {
        id: 'off_steel_col_1',
        name: 'Perimeter Steel Column 1',
        category: 'structure',
        section: 'building',
        primitive: 'column',
        position: [-10, 4, -12],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 0.5, height: 8.4, depth: 0.5 },
        material: MATERIAL_PRESETS.structural_steel_dark,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, isLoadBearing: true },
      },
      {
        id: 'off_steel_col_2',
        name: 'Perimeter Steel Column 2',
        category: 'structure',
        section: 'building',
        primitive: 'column',
        position: [10, 4, -12],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 0.5, height: 8.4, depth: 0.5 },
        material: MATERIAL_PRESETS.structural_steel_dark,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, isLoadBearing: true },
      },
      {
        id: 'off_steel_col_3',
        name: 'Perimeter Steel Column 3',
        category: 'structure',
        section: 'building',
        primitive: 'column',
        position: [-10, 4, 12],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 0.5, height: 8.4, depth: 0.5 },
        material: MATERIAL_PRESETS.structural_steel_dark,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, isLoadBearing: true },
      },
      {
        id: 'off_steel_col_4',
        name: 'Perimeter Steel Column 4',
        category: 'structure',
        section: 'building',
        primitive: 'column',
        position: [10, 4, 12],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 0.5, height: 8.4, depth: 0.5 },
        material: MATERIAL_PRESETS.structural_steel_dark,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0, isLoadBearing: true },
      },
      // 360 Full Curtain Glazing
      {
        id: 'off_curtain_wall_s',
        name: 'South Triple-Glazed Facade',
        category: 'envelope',
        section: 'building',
        primitive: 'window',
        position: [0, 4.2, 12.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 22, height: 8.2, depth: 0.15 },
        material: MATERIAL_PRESETS.curtain_wall_glass,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0 },
      },
      {
        id: 'off_curtain_wall_n',
        name: 'North Facade Low-E Glazing',
        category: 'envelope',
        section: 'building',
        primitive: 'window',
        position: [0, 4.2, -12.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 22, height: 8.2, depth: 0.15 },
        material: MATERIAL_PRESETS.curtain_wall_glass,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 0 },
      },
      // Mezzanine Floor Slab with Atrium Cutout
      {
        id: 'off_mezzanine_slab',
        name: 'Level 1 Engineering Mezzanine Floor',
        category: 'structure',
        section: 'building',
        primitive: 'slab',
        position: [0, 4.2, -3],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 22, height: 0.35, depth: 16 },
        material: MATERIAL_PRESETS.warm_oak_timber,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 1 },
      },
      // Roof Steel Truss Structure
      {
        id: 'off_roof_slab',
        name: 'Long-Span Steel Roof Diagrid',
        category: 'structure',
        section: 'building',
        primitive: 'slab',
        position: [0, 8.4, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 25, height: 0.4, depth: 29 },
        material: MATERIAL_PRESETS.structural_steel_dark,
        visible: true,
        locked: false,
        architecturalProps: { floorLevel: 2 },
      },
    ],
  },
};
