import { CADObject, DeviceConfig } from '../../types/cad';
import { MATERIAL_PRESETS } from '../../utils/materials';

export interface DevicePresetData {
  config: DeviceConfig;
  objects: CADObject[];
}

export const DEVICE_PRESETS: Record<string, DevicePresetData> = {
  smartphone_pro: {
    config: {
      id: 'smartphone_pro',
      name: 'Titan Titanium Smartphone Pro',
      type: 'smartphone',
      description: 'Precision engineered 6.7-inch flagship device with titanium enclosure, 3-layer internal stack, A18 Pro SoC, and periscope triple optics.',
      dimensions: { width: 76, height: 160, depth: 8.2, cornerRadius: 18, wallThickness: 1.2 },
      casingColor: '#383b42',
      accentColor: '#06b6d4',
      screenOn: true,
      screenEmissiveColor: '#0284c7',
      explodedAmount: 0,
      slicePlaneEnabled: false,
      sliceAxis: 'y',
      sliceOffset: 0,
      thermalSimActive: false,
      pcbTracesVisible: true,
    },
    objects: [
      // 1. Back Glass Panel
      {
        id: 'sp_back_glass',
        name: 'Frosted Matte Back Glass',
        category: 'casing',
        section: 'technology',
        primitive: 'rounded_box',
        position: [0, 0, -3.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 75, height: 159, depth: 0.8, bevelRadius: 2 },
        material: {
          ...MATERIAL_PRESETS.matte_black_polycarbonate,
          id: 'mat_sp_back',
          color: '#262930',
          roughness: 0.4,
          metalness: 0.1,
        },
        visible: true,
        locked: false,
        explodeDirection: [0, 0, -1],
        explodeDistance: 60,
      },
      // 2. Titanium Outer Chassis Frame
      {
        id: 'sp_chassis_frame',
        name: 'Grade 5 Titanium Band Chassis',
        category: 'casing',
        section: 'technology',
        primitive: 'rounded_box',
        position: [0, 0, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 76.5, height: 160.5, depth: 8.0, bevelRadius: 3.5 },
        material: MATERIAL_PRESETS.polished_titanium,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, 0],
        explodeDistance: 0,
      },
      // 3. Wireless Charging Coil & Magnet Ring
      {
        id: 'sp_magsafe_coil',
        name: 'Qi2 Magnetic Inductive Coil',
        category: 'power',
        section: 'technology',
        primitive: 'torus',
        position: [0, -5, -2.6],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 38, height: 38, depth: 0.5, radius: 18 },
        material: MATERIAL_PRESETS.copper_heatsink,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, -1],
        explodeDistance: 42,
        electricalProps: { voltage: 15, currentMa: 1000, heatWattage: 2.2, partNumber: 'MAG-QI2-15W', temperatureC: 38 },
      },
      // 4. Lithium-Polymer Battery Pack
      {
        id: 'sp_battery',
        name: '4,850 mAh Li-Ion Graphene Cell',
        category: 'power',
        section: 'technology',
        primitive: 'box',
        position: [-10, -16, -1.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 44, height: 98, depth: 4.2 },
        material: {
          ...MATERIAL_PRESETS.carbon_fiber_composite,
          id: 'mat_sp_batt',
          color: '#1a1d20',
          roughness: 0.3,
        },
        visible: true,
        locked: false,
        explodeDirection: [-0.6, 0, -0.6],
        explodeDistance: 35,
        electricalProps: { voltage: 3.87, currentMa: 4850, heatWattage: 4.5, partNumber: 'BAT-LIPO-4850', temperatureC: 34 },
      },
      // 5. Main Logic Board (PCB)
      {
        id: 'sp_main_pcb',
        name: 'Multi-Layer Substrate PCB (FR4-HiTg)',
        category: 'pcb',
        section: 'technology',
        primitive: 'pcb_board',
        position: [0, 36, -0.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 68, height: 60, depth: 1.2 },
        material: MATERIAL_PRESETS.pcb_matte_black,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, 0.4],
        explodeDistance: 30,
        electricalProps: { voltage: 1.1, currentMa: 3200, heatWattage: 9.8, partNumber: 'MLB-PRO-A18', temperatureC: 48 },
      },
      // 6. A18 SoC Processor Chip & Copper Heat Spreader
      {
        id: 'sp_soc_chip',
        name: '3nm Ultra SoC Processor + NPU',
        category: 'internal',
        section: 'technology',
        primitive: 'chip_ic',
        position: [12, 38, 0.2],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 16, height: 16, depth: 1.5 },
        material: MATERIAL_PRESETS.gold_electroless_trace,
        visible: true,
        locked: false,
        explodeDirection: [0.3, 0.2, 0.8],
        explodeDistance: 45,
        electricalProps: { voltage: 0.95, currentMa: 5400, heatWattage: 12.0, partNumber: 'SOC-3NM-OCTA', temperatureC: 62 },
      },
      // 7. Vapor Chamber Cooling Copper Plate
      {
        id: 'sp_vapor_chamber',
        name: 'Vapor Chamber Graphite Dissipator',
        category: 'internal',
        section: 'technology',
        primitive: 'box',
        position: [4, 25, 0.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 60, height: 80, depth: 0.3 },
        material: MATERIAL_PRESETS.copper_heatsink,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, 0.6],
        explodeDistance: 38,
      },
      // 8. Triple Camera Module Plateau Housing
      {
        id: 'sp_camera_housing',
        name: 'Aerospace Ceramic Camera Island',
        category: 'optics',
        section: 'technology',
        primitive: 'rounded_box',
        position: [-16, 46, -4.6],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 36, height: 38, depth: 2.8, bevelRadius: 4 },
        material: MATERIAL_PRESETS.anodized_aluminum_spacegray,
        visible: true,
        locked: false,
        explodeDirection: [-0.4, 0.4, -1],
        explodeDistance: 70,
      },
      // 9. Main 48MP Wide Camera Lens
      {
        id: 'sp_lens_main',
        name: '48MP f/1.78 Main Sensor (7P Lens)',
        category: 'optics',
        section: 'technology',
        primitive: 'cylinder',
        position: [-22, 54, -5.8],
        rotation: [Math.PI / 2, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 13, height: 2.5, depth: 13, radius: 6.5 },
        material: MATERIAL_PRESETS.sapphire_camera_glass,
        visible: true,
        locked: false,
        explodeDirection: [-0.6, 0.6, -1.2],
        explodeDistance: 85,
        electricalProps: { voltage: 2.8, currentMa: 450, heatWattage: 1.2, partNumber: 'OPT-48MP-OIS', temperatureC: 36 },
      },
      // 10. 5x Periscope Telephoto Lens
      {
        id: 'sp_lens_tele',
        name: '12MP 5x Tetraprism Telephoto',
        category: 'optics',
        section: 'technology',
        primitive: 'cylinder',
        position: [-22, 38, -5.8],
        rotation: [Math.PI / 2, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 13, height: 2.5, depth: 13, radius: 6.5 },
        material: MATERIAL_PRESETS.sapphire_camera_glass,
        visible: true,
        locked: false,
        explodeDirection: [-0.6, 0.2, -1.2],
        explodeDistance: 85,
      },
      // 11. Ultra-Wide Lens + LiDAR Scanner
      {
        id: 'sp_lens_wide',
        name: '120° Ultra-Wide + LiDAR Scanner',
        category: 'optics',
        section: 'technology',
        primitive: 'cylinder',
        position: [-8, 46, -5.8],
        rotation: [Math.PI / 2, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 13, height: 2.5, depth: 13, radius: 6.5 },
        material: MATERIAL_PRESETS.sapphire_camera_glass,
        visible: true,
        locked: false,
        explodeDirection: [-0.2, 0.4, -1.2],
        explodeDistance: 85,
      },
      // 12. USB-C Port & Thunderbolt Controller
      {
        id: 'sp_usbc_port',
        name: 'USB 3.2 Gen2x2 (10Gbps) Type-C Port',
        category: 'io',
        section: 'technology',
        primitive: 'port_usbc',
        position: [0, -78, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 9.5, height: 3.8, depth: 7 },
        material: MATERIAL_PRESETS.polished_titanium,
        visible: true,
        locked: false,
        explodeDirection: [0, -1, 0],
        explodeDistance: 35,
      },
      // 13. Taptic Linear Actuator (Haptic Motor)
      {
        id: 'sp_taptic_engine',
        name: 'Wideband Linear Haptic Actuator',
        category: 'internal',
        section: 'technology',
        primitive: 'box',
        position: [20, -68, -0.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 22, height: 12, depth: 3.5 },
        material: MATERIAL_PRESETS.anodized_aluminum_silver,
        visible: true,
        locked: false,
        explodeDirection: [0.6, -0.6, -0.4],
        explodeDistance: 30,
      },
      // 14. Active OLED 120Hz ProMotion Display Panel
      {
        id: 'sp_oled_display',
        name: '6.7" LTPO Super Retina OLED (2000 nits)',
        category: 'optics',
        section: 'technology',
        primitive: 'screen_panel',
        position: [0, 0, 3.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 73.5, height: 157.5, depth: 0.6, bevelRadius: 2.8 },
        material: MATERIAL_PRESETS.oled_screen_cyber,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, 1],
        explodeDistance: 50,
        electricalProps: { voltage: 3.3, currentMa: 750, heatWattage: 2.5, partNumber: 'DSP-OLED-67-120', temperatureC: 37 },
      },
      // 15. Ceramic Shield Front Toughened Glass
      {
        id: 'sp_front_glass',
        name: 'Nanocrystal Ceramic Shield Glass',
        category: 'casing',
        section: 'technology',
        primitive: 'rounded_box',
        position: [0, 0, 4.3],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 75, height: 159, depth: 0.6, bevelRadius: 3 },
        material: {
          ...MATERIAL_PRESETS.sapphire_camera_glass,
          id: 'mat_sp_front_glass',
          opacity: 0.5,
        },
        visible: true,
        locked: false,
        explodeDirection: [0, 0, 1],
        explodeDistance: 68,
      },
    ],
  },

  drone_quadcopter: {
    config: {
      id: 'drone_quadcopter',
      name: 'AeroStrike X-4 Autonomous Drone',
      type: 'drone',
      description: 'High-performance carbon fiber quadcopter with modular 4K 3-axis gimbal, 4S LiPo battery, obstacle avoidance radar, and high-KV brushless motors.',
      dimensions: { width: 220, height: 85, depth: 220, cornerRadius: 10, wallThickness: 2 },
      casingColor: '#1a1d24',
      accentColor: '#10b981',
      screenOn: true,
      screenEmissiveColor: '#10b981',
      explodedAmount: 0,
      slicePlaneEnabled: false,
      sliceAxis: 'y',
      sliceOffset: 0,
      thermalSimActive: false,
      pcbTracesVisible: true,
    },
    objects: [
      // Central Carbon Monocoque Core Body
      {
        id: 'dr_fuselage_top',
        name: 'Carbon Aerodynamic Fuselage Top Shell',
        category: 'casing',
        section: 'technology',
        primitive: 'rounded_box',
        position: [0, 12, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 70, height: 24, depth: 110, bevelRadius: 5 },
        material: MATERIAL_PRESETS.carbon_fiber_composite,
        visible: true,
        locked: false,
        explodeDirection: [0, 1, 0],
        explodeDistance: 45,
      },
      {
        id: 'dr_fuselage_bottom',
        name: 'Lower Chassis & Battery Bay',
        category: 'casing',
        section: 'technology',
        primitive: 'rounded_box',
        position: [0, -10, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 68, height: 20, depth: 105, bevelRadius: 4 },
        material: MATERIAL_PRESETS.matte_black_polycarbonate,
        visible: true,
        locked: false,
        explodeDirection: [0, -1, 0],
        explodeDistance: 40,
      },
      // 4 Carbon Fiber Arms
      {
        id: 'dr_arm_fl',
        name: 'Front-Left Carbon Arm & Esc Tube',
        category: 'structure',
        section: 'technology',
        primitive: 'box',
        position: [-65, 0, 65],
        rotation: [0, Math.PI / 4, 0],
        scale: [1, 1, 1],
        dimensions: { width: 14, height: 10, depth: 110 },
        material: MATERIAL_PRESETS.carbon_fiber_composite,
        visible: true,
        locked: false,
        explodeDirection: [-1, 0, 1],
        explodeDistance: 35,
      },
      {
        id: 'dr_arm_fr',
        name: 'Front-Right Carbon Arm & Esc Tube',
        category: 'structure',
        section: 'technology',
        primitive: 'box',
        position: [65, 0, 65],
        rotation: [0, -Math.PI / 4, 0],
        scale: [1, 1, 1],
        dimensions: { width: 14, height: 10, depth: 110 },
        material: MATERIAL_PRESETS.carbon_fiber_composite,
        visible: true,
        locked: false,
        explodeDirection: [1, 0, 1],
        explodeDistance: 35,
      },
      {
        id: 'dr_arm_bl',
        name: 'Rear-Left Carbon Arm & Esc Tube',
        category: 'structure',
        section: 'technology',
        primitive: 'box',
        position: [-65, 0, -65],
        rotation: [0, -Math.PI / 4, 0],
        scale: [1, 1, 1],
        dimensions: { width: 14, height: 10, depth: 110 },
        material: MATERIAL_PRESETS.carbon_fiber_composite,
        visible: true,
        locked: false,
        explodeDirection: [-1, 0, -1],
        explodeDistance: 35,
      },
      {
        id: 'dr_arm_br',
        name: 'Rear-Right Carbon Arm & Esc Tube',
        category: 'structure',
        section: 'technology',
        primitive: 'box',
        position: [65, 0, -65],
        rotation: [0, Math.PI / 4, 0],
        scale: [1, 1, 1],
        dimensions: { width: 14, height: 10, depth: 110 },
        material: MATERIAL_PRESETS.carbon_fiber_composite,
        visible: true,
        locked: false,
        explodeDirection: [1, 0, -1],
        explodeDistance: 35,
      },
      // 4 Brushless Motors
      {
        id: 'dr_motor_fl',
        name: 'Brushless 2306 2450KV Motor FL',
        category: 'internal',
        section: 'technology',
        primitive: 'cylinder',
        position: [-105, 8, 105],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 28, height: 18, depth: 28, radius: 14 },
        material: MATERIAL_PRESETS.anodized_aluminum_midnight,
        visible: true,
        locked: false,
        explodeDirection: [-1, 0.5, 1],
        explodeDistance: 45,
        electricalProps: { voltage: 14.8, currentMa: 15000, heatWattage: 18, partNumber: 'MTR-BL-2306', temperatureC: 55 },
      },
      {
        id: 'dr_motor_fr',
        name: 'Brushless 2306 2450KV Motor FR',
        category: 'internal',
        section: 'technology',
        primitive: 'cylinder',
        position: [105, 8, 105],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 28, height: 18, depth: 28, radius: 14 },
        material: MATERIAL_PRESETS.anodized_aluminum_midnight,
        visible: true,
        locked: false,
        explodeDirection: [1, 0.5, 1],
        explodeDistance: 45,
        electricalProps: { voltage: 14.8, currentMa: 15000, heatWattage: 18, partNumber: 'MTR-BL-2306', temperatureC: 55 },
      },
      {
        id: 'dr_motor_bl',
        name: 'Brushless 2306 2450KV Motor BL',
        category: 'internal',
        section: 'technology',
        primitive: 'cylinder',
        position: [-105, 8, -105],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 28, height: 18, depth: 28, radius: 14 },
        material: MATERIAL_PRESETS.anodized_aluminum_midnight,
        visible: true,
        locked: false,
        explodeDirection: [-1, 0.5, -1],
        explodeDistance: 45,
        electricalProps: { voltage: 14.8, currentMa: 15000, heatWattage: 18, partNumber: 'MTR-BL-2306', temperatureC: 55 },
      },
      {
        id: 'dr_motor_br',
        name: 'Brushless 2306 2450KV Motor BR',
        category: 'internal',
        section: 'technology',
        primitive: 'cylinder',
        position: [105, 8, -105],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 28, height: 18, depth: 28, radius: 14 },
        material: MATERIAL_PRESETS.anodized_aluminum_midnight,
        visible: true,
        locked: false,
        explodeDirection: [1, 0.5, -1],
        explodeDistance: 45,
        electricalProps: { voltage: 14.8, currentMa: 15000, heatWattage: 18, partNumber: 'MTR-BL-2306', temperatureC: 55 },
      },
      // 4 Propellers
      {
        id: 'dr_prop_fl',
        name: '5.1" Low-Noise Tri-Blade Propeller FL',
        category: 'custom',
        section: 'technology',
        primitive: 'torus',
        position: [-105, 20, 105],
        rotation: [Math.PI / 2, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 90, height: 90, depth: 4, radius: 45 },
        material: MATERIAL_PRESETS.led_indicator_emerald,
        visible: true,
        locked: false,
        explodeDirection: [-1, 1, 1],
        explodeDistance: 65,
      },
      {
        id: 'dr_prop_fr',
        name: '5.1" Low-Noise Tri-Blade Propeller FR',
        category: 'custom',
        section: 'technology',
        primitive: 'torus',
        position: [105, 20, 105],
        rotation: [Math.PI / 2, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 90, height: 90, depth: 4, radius: 45 },
        material: MATERIAL_PRESETS.led_indicator_emerald,
        visible: true,
        locked: false,
        explodeDirection: [1, 1, 1],
        explodeDistance: 65,
      },
      // Flight Controller & ESC Stack (PCB)
      {
        id: 'dr_flight_controller',
        name: 'F722 Flight Controller + 4-in-1 ESC',
        category: 'pcb',
        section: 'technology',
        primitive: 'pcb_board',
        position: [0, 0, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 36, height: 6, depth: 36 },
        material: MATERIAL_PRESETS.pcb_classic_green,
        visible: true,
        locked: false,
        explodeDirection: [0, 0.4, 0],
        explodeDistance: 25,
        electricalProps: { voltage: 5.0, currentMa: 1200, heatWattage: 4.5, partNumber: 'FC-STM32F7-ICM42688', temperatureC: 46 },
      },
      // 4S LiPo Smart Battery
      {
        id: 'dr_lipo_battery',
        name: '4S 2200mAh 120C LiPo Pack',
        category: 'power',
        section: 'technology',
        primitive: 'box',
        position: [0, -4, -12],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 38, height: 32, depth: 75 },
        material: MATERIAL_PRESETS.anodized_aluminum_spacegray,
        visible: true,
        locked: false,
        explodeDirection: [0, -0.8, -0.6],
        explodeDistance: 50,
        electricalProps: { voltage: 14.8, currentMa: 2200, heatWattage: 8.0, partNumber: 'BAT-4S-2200MAH', temperatureC: 41 },
      },
      // 3-Axis Gimbal & 4K Camera
      {
        id: 'dr_gimbal_camera',
        name: '4K/60fps 3-Axis Brushless Gimbal Optical Camera',
        category: 'optics',
        section: 'technology',
        primitive: 'camera_lens',
        position: [0, -18, 52],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 32, height: 32, depth: 36, radius: 15 },
        material: MATERIAL_PRESETS.anodized_aluminum_midnight,
        visible: true,
        locked: false,
        explodeDirection: [0, -0.6, 1],
        explodeDistance: 55,
        electricalProps: { voltage: 5.0, currentMa: 800, heatWattage: 3.2, partNumber: 'CAM-4K-GIMBAL-V2', temperatureC: 39 },
      },
      // Obstacle LiDAR & Forward Sensor Dome
      {
        id: 'dr_lidar_sensor',
        name: '360° LiDAR Collision Avoidance Puck',
        category: 'internal',
        section: 'technology',
        primitive: 'cylinder',
        position: [0, 26, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 26, height: 12, depth: 26, radius: 13 },
        material: MATERIAL_PRESETS.led_indicator_cyan,
        visible: true,
        locked: false,
        explodeDirection: [0, 1.2, 0],
        explodeDistance: 60,
        electricalProps: { voltage: 5.0, currentMa: 350, heatWattage: 1.5, partNumber: 'LIDAR-TOF-360', temperatureC: 35 },
      },
    ],
  },

  vr_headset: {
    config: {
      id: 'vr_headset',
      name: 'Spatial Vision Pro VR Headset',
      type: 'vr_headset',
      description: 'Next-generation spatial computing headset featuring dual 4K micro-OLED optical lenses, forward pass-through 3D cameras, magnesium alloy frame, and counterweighted halo strap.',
      dimensions: { width: 180, height: 95, depth: 140, cornerRadius: 22, wallThickness: 2.5 },
      casingColor: '#1e2024',
      accentColor: '#38bdf8',
      screenOn: true,
      screenEmissiveColor: '#38bdf8',
      explodedAmount: 0,
      slicePlaneEnabled: false,
      sliceAxis: 'z',
      sliceOffset: 0,
      thermalSimActive: false,
      pcbTracesVisible: true,
    },
    objects: [
      // Curved Front Glass Visor
      {
        id: 'vr_front_visor',
        name: '3D Curved Optical Glass Front Visor',
        category: 'casing',
        section: 'technology',
        primitive: 'rounded_box',
        position: [0, 0, 48],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 172, height: 86, depth: 8, bevelRadius: 18 },
        material: {
          ...MATERIAL_PRESETS.sapphire_camera_glass,
          id: 'mat_vr_visor',
          color: '#0a0d14',
          opacity: 0.7,
        },
        visible: true,
        locked: false,
        explodeDirection: [0, 0, 1],
        explodeDistance: 65,
      },
      // Front Pass-Through 3D Cameras
      {
        id: 'vr_camera_l',
        name: 'High-Speed Passthrough Camera (Left)',
        category: 'optics',
        section: 'technology',
        primitive: 'camera_lens',
        position: [-42, 6, 46],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 12, height: 12, depth: 10, radius: 6 },
        material: MATERIAL_PRESETS.led_indicator_cyan,
        visible: true,
        locked: false,
        explodeDirection: [-0.4, 0.1, 1.2],
        explodeDistance: 80,
      },
      {
        id: 'vr_camera_r',
        name: 'High-Speed Passthrough Camera (Right)',
        category: 'optics',
        section: 'technology',
        primitive: 'camera_lens',
        position: [42, 6, 46],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 12, height: 12, depth: 10, radius: 6 },
        material: MATERIAL_PRESETS.led_indicator_cyan,
        visible: true,
        locked: false,
        explodeDirection: [0.4, 0.1, 1.2],
        explodeDistance: 80,
      },
      // Magnesium Alloy Main Structure Frame
      {
        id: 'vr_chassis_frame',
        name: 'Aviation Magnesium Chassis Frame',
        category: 'casing',
        section: 'technology',
        primitive: 'rounded_box',
        position: [0, 0, 20],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 175, height: 90, depth: 45, bevelRadius: 16 },
        material: MATERIAL_PRESETS.anodized_aluminum_spacegray,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, 0],
        explodeDistance: 0,
      },
      // Dual Pancake Optical Lens Barrels
      {
        id: 'vr_lens_left',
        name: 'Pancake Optical Lens Stack (Left Eye)',
        category: 'optics',
        section: 'technology',
        primitive: 'cylinder',
        position: [-32, 0, -4],
        rotation: [Math.PI / 2, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 44, height: 22, depth: 44, radius: 22 },
        material: MATERIAL_PRESETS.sapphire_camera_glass,
        visible: true,
        locked: false,
        explodeDirection: [-0.5, 0, -0.8],
        explodeDistance: 45,
      },
      {
        id: 'vr_lens_right',
        name: 'Pancake Optical Lens Stack (Right Eye)',
        category: 'optics',
        section: 'technology',
        primitive: 'cylinder',
        position: [32, 0, -4],
        rotation: [Math.PI / 2, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 44, height: 22, depth: 44, radius: 22 },
        material: MATERIAL_PRESETS.sapphire_camera_glass,
        visible: true,
        locked: false,
        explodeDirection: [0.5, 0, -0.8],
        explodeDistance: 45,
      },
      // Dual 4K Micro-OLED Panels
      {
        id: 'vr_panel_left',
        name: 'Micro-OLED Display 4K HDR (Left)',
        category: 'optics',
        section: 'technology',
        primitive: 'screen_panel',
        position: [-32, 0, 10],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 34, height: 28, depth: 1.2 },
        material: MATERIAL_PRESETS.oled_screen_active,
        visible: true,
        locked: false,
        explodeDirection: [-0.3, 0, 0.4],
        explodeDistance: 30,
        electricalProps: { voltage: 3.3, currentMa: 650, heatWattage: 2.1, partNumber: 'OLED-4K-MICRO-L', temperatureC: 38 },
      },
      {
        id: 'vr_panel_right',
        name: 'Micro-OLED Display 4K HDR (Right)',
        category: 'optics',
        section: 'technology',
        primitive: 'screen_panel',
        position: [32, 0, 10],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 34, height: 28, depth: 1.2 },
        material: MATERIAL_PRESETS.oled_screen_active,
        visible: true,
        locked: false,
        explodeDirection: [0.3, 0, 0.4],
        explodeDistance: 30,
        electricalProps: { voltage: 3.3, currentMa: 650, heatWattage: 2.1, partNumber: 'OLED-4K-MICRO-R', temperatureC: 38 },
      },
      // Spatial Audio Stems & Halo Headstrap
      {
        id: 'vr_halo_strap',
        name: 'Counterbalanced Ergonomic Halo Strap & Dial',
        category: 'casing',
        section: 'technology',
        primitive: 'torus',
        position: [0, 0, -55],
        rotation: [0, 0, 0],
        scale: [1, 0.7, 1.2],
        dimensions: { width: 190, height: 190, depth: 14, radius: 95 },
        material: MATERIAL_PRESETS.silicone_rubber_grip,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, -1],
        explodeDistance: 50,
      },
      // Rear Counterweight Battery Pack
      {
        id: 'vr_rear_battery',
        name: 'Rear Counterweight Battery Module (35.9Wh)',
        category: 'power',
        section: 'technology',
        primitive: 'rounded_box',
        position: [0, -5, -165],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 85, height: 42, depth: 22, bevelRadius: 6 },
        material: MATERIAL_PRESETS.anodized_aluminum_spacegray,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, -1.4],
        explodeDistance: 80,
        electricalProps: { voltage: 7.4, currentMa: 4850, heatWattage: 3.5, partNumber: 'BAT-VR-HALO-35WH', temperatureC: 32 },
      },
    ],
  },

  smartwatch_ultra: {
    config: {
      id: 'smartwatch_ultra',
      name: 'Chronos Ultra Titanium Smartwatch',
      type: 'smartwatch',
      description: 'Rugged titanium aerospace smartwatch with sapphire crystal dial, rotating knurled digital crown, biosensor optical array, and dive-grade silicone band.',
      dimensions: { width: 49, height: 44, depth: 14.4, cornerRadius: 14, wallThickness: 2 },
      casingColor: '#94a3b8',
      accentColor: '#f97316',
      screenOn: true,
      screenEmissiveColor: '#f97316',
      explodedAmount: 0,
      slicePlaneEnabled: false,
      sliceAxis: 'z',
      sliceOffset: 0,
      thermalSimActive: false,
      pcbTracesVisible: true,
    },
    objects: [
      // Titanium Watch Case Body
      {
        id: 'sw_case_body',
        name: 'Grade 5 Brushed Titanium Watch Case (49mm)',
        category: 'casing',
        section: 'technology',
        primitive: 'rounded_box',
        position: [0, 0, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 44, height: 49, depth: 14, bevelRadius: 8 },
        material: MATERIAL_PRESETS.polished_titanium,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, 0],
        explodeDistance: 0,
      },
      // Flat Sapphire Crystal Top Glass
      {
        id: 'sw_sapphire_glass',
        name: 'Raised Flat Sapphire Crystal Cover',
        category: 'casing',
        section: 'technology',
        primitive: 'cylinder',
        position: [0, 0, 7.8],
        rotation: [Math.PI / 2, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 38, height: 1.8, depth: 38, radius: 19 },
        material: MATERIAL_PRESETS.sapphire_camera_glass,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, 1],
        explodeDistance: 35,
      },
      // High-Brightness LTPO OLED Dial Screen
      {
        id: 'sw_oled_screen',
        name: '1.92" LTPO Always-On OLED (3000 nits)',
        category: 'optics',
        section: 'technology',
        primitive: 'screen_panel',
        position: [0, 0, 6.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 36, height: 41, depth: 0.8, bevelRadius: 6 },
        material: MATERIAL_PRESETS.oled_screen_cyber,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, 1],
        explodeDistance: 25,
        electricalProps: { voltage: 3.3, currentMa: 180, heatWattage: 0.6, partNumber: 'SW-OLED-LTPO-3000', temperatureC: 32 },
      },
      // Rotating Knurled Digital Crown
      {
        id: 'sw_digital_crown',
        name: 'Knurled Titanium Digital Crown + Haptic Sensor',
        category: 'io',
        section: 'technology',
        primitive: 'cylinder',
        position: [24, 10, 2],
        rotation: [0, 0, Math.PI / 2],
        scale: [1, 1, 1],
        dimensions: { width: 8, height: 6, depth: 8, radius: 4 },
        material: MATERIAL_PRESETS.polished_titanium,
        visible: true,
        locked: false,
        explodeDirection: [1, 0, 0],
        explodeDistance: 28,
      },
      // International Orange Action Button
      {
        id: 'sw_action_button',
        name: 'Customizable International Orange Button',
        category: 'io',
        section: 'technology',
        primitive: 'rounded_box',
        position: [-23, -4, 1],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 3, height: 16, depth: 6, bevelRadius: 1.5 },
        material: MATERIAL_PRESETS.led_indicator_orange,
        visible: true,
        locked: false,
        explodeDirection: [-1, 0, 0],
        explodeDistance: 26,
      },
      // SiP Mainboard Package
      {
        id: 'sw_sip_mainboard',
        name: 'Dual-Core S9 SiP Main Computing Module',
        category: 'pcb',
        section: 'technology',
        primitive: 'pcb_board',
        position: [0, 0, 1],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 34, height: 38, depth: 2.2 },
        material: MATERIAL_PRESETS.pcb_matte_black,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, -0.2],
        explodeDistance: 15,
        electricalProps: { voltage: 3.7, currentMa: 350, heatWattage: 1.4, partNumber: 'SIP-S9-DUAL', temperatureC: 35 },
      },
      // Bio-Sensor Ceramic Optical Back
      {
        id: 'sw_biosensor_back',
        name: 'Zirconia Ceramic Bio-Sensor Optical Heart/ECG Array',
        category: 'internal',
        section: 'technology',
        primitive: 'cylinder',
        position: [0, 0, -7.5],
        rotation: [Math.PI / 2, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 34, height: 2, depth: 34, radius: 17 },
        material: MATERIAL_PRESETS.led_indicator_emerald,
        visible: true,
        locked: false,
        explodeDirection: [0, 0, -1],
        explodeDistance: 32,
        electricalProps: { voltage: 3.3, currentMa: 90, heatWattage: 0.3, partNumber: 'BIO-PPG-ECG-4CH', temperatureC: 31 },
      },
      // Ocean High-Durability Silicone Loop Bands
      {
        id: 'sw_band_top',
        name: 'Molded Fluoropolymer Wave Band (Top)',
        category: 'casing',
        section: 'technology',
        primitive: 'box',
        position: [0, 52, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 26, height: 60, depth: 5 },
        material: MATERIAL_PRESETS.silicone_rubber_grip,
        visible: true,
        locked: false,
        explodeDirection: [0, 1, 0],
        explodeDistance: 45,
      },
      {
        id: 'sw_band_bottom',
        name: 'Molded Fluoropolymer Wave Band (Bottom)',
        category: 'casing',
        section: 'technology',
        primitive: 'box',
        position: [0, -52, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        dimensions: { width: 26, height: 60, depth: 5 },
        material: MATERIAL_PRESETS.silicone_rubber_grip,
        visible: true,
        locked: false,
        explodeDirection: [0, -1, 0],
        explodeDistance: 45,
      },
    ],
  },
};
